export const iconMapping = {
    'iphone': '📱',
    'phone': '📱',
    'móvil': '📱',
    'celular': '📱',
    'smartphone': '📱',
    'samsung': '📱',
    'huawei': '📱',
    'xiaomi': '📱',
    'oppo': '📱',
    'vivo': '📱',
    'oneplus': '📱',
    'pixel': '📱',
    'motorola': '📱',
    
    'laptop': '💻',
    'notebook': '💻',
    'macbook': '💻',
    'dell': '💻',
    'hp': '💻',
    'lenovo': '💻',
    'asus': '💻',
    'acer': '💻',
    'computadora': '💻',
    'pc': '🖥️',
    'desktop': '🖥️',
    'workstation': '🖥️',
    'imac': '🖥️',
    'monitor': '🖥️',
    'pantalla': '🖥️',
    'display': '🖥️',
    
    'headphones': '🎧',
    'auriculares': '🎧',
    'audífonos': '🎧',
    'bluetooth': '🎧',
    'airpods': '🎧',
    'beats': '🎧',
    'sony': '🎧',
    'bose': '🎧',
    'jbl': '🎧',
    'sennheiser': '🎧',
    'skullcandy': '🎧',
    'speaker': '🔊',
    'altavoz': '🔊',
    'bocina': '🔊',
    'parlante': '🔊',
    'soundbar': '🔊',
    'subwoofer': '🔊',
    'micrófono': '�',
    'microphone': '�',
    'mic': '🎤',
    'radio': '📻',
    'walkman': '📻',
    'reproductor': '🎵',
    'mp3': '🎵',
    'ipod': '🎵',
    
    'gaming': '🎮',
    'gamer': '🎮',
    'xbox': '🎮',
    'playstation': '🎮',
    'ps5': '🎮',
    'ps4': '🎮',
    'nintendo': '🎮',
    'switch': '🎮',
    'steam': '🎮',
    'joystick': '🎮',
    'gamepad': '🎮',
    'control': '🎮',
    'mando': '🎮',
    'mouse': '🖱️',
    'ratón': '🖱️',
    'teclado': '⌨️',
    'keyboard': '⌨️',
    'mechanical': '⌨️',
    'webcam': '📹',
    'cámara web': '📹',
    'streaming': '📹',
    'twitch': '📹',
    'youtube': '📹',
    
    'tablet': '📱',
    'ipad': '📱',
    'galaxy tab': '📱',
    'surface': '📱',
    'kindle': '📖',
    'e-reader': '📖',
    'lector': '📖',
    
    'cable': '🔌',
    'cargador': '🔌',
    'charger': '🔌',
    'usb': '🔌',
    'adaptador': '🔌',
    'hub': '🔌',
    'splitter': '🔌',
    'extensión': '🔌',
    'powerbank': '🔋',
    'batería': '🔋',
    'power bank': '🔋',
    'case': '�',
    'funda': '�',
    'protector': '🛡️',
    'vidrio': '🛡️',
    'mica': '🛡️',
    'tempered': '🛡️',
    'soporte': '📱',
    'stand': '📱',
    'tripod': '📷',
    'trípode': '📷',
    'selfie stick': '📱',
    'palo selfie': '📱',
    
    'refrigerador': '❄️',
    'nevera': '❄️',
    'frigorífico': '❄️',
    'congelador': '❄️',
    'lavadora': '🫧',
    'secadora': '🫧',
    'lavavajillas': '🫧',
    'estufa': '🔥',
    'cocina': '🔥',
    'horno': '🔥',
    'microondas': '📦',
    'aires acondicionado': '❄️',
    'aire': '❄️',
    'ventilador': '🌪️',
    'calentador': '🔥',
    'boiler': '🔥',
    
    'licuadora': '🥤',
    'batidora': '🥄',
    'mixer': '🥄',
    'procesador': '🥄',
    'extractor': '🥤',
    'juicer': '🥤',
    'cafetera': '☕',
    'coffee': '☕',
    'espresso': '☕',
    'tostadora': '🍞',
    'toaster': '🍞',
    'sandwichera': '🥪',
    'plancha': '👔',
    'iron': '�',
    'aspiradora': '🧹',
    'vacuum': '🧹',
    'robot': '🤖',
    'roomba': '🤖',
    'freidora': '🍟',
    'air fryer': '🍟',
    'olla': '🍲',
    'slow cooker': '🍲',
    'pressure cooker': '🍲',
    'rice cooker': '🍚',
    'arrocera': '🍚',
    
    'televisor': '📺',
    'tv': '📺',
    'smart tv': '📺',
    'led': '📺',
    'oled': '📺',
    'qled': '📺',
    '4k': '📺',
    '8k': '📺',
    'roku': '📺',
    'chromecast': '📺',
    'apple tv': '📺',
    'fire stick': '📺',
    'projector': '📽️',
    'proyector': '📽️',
    
    'camisa': '👔',
    'shirt': '👔',
    'blusa': '👚',
    'blouse': '👚',
    'pantalón': '👖',
    'pants': '👖',
    'jeans': '👖',
    'falda': '👗',
    'vestido': '👗',
    'dress': '👗',
    'zapatos': '👟',
    'shoes': '👟',
    'sneakers': '👟',
    'tenis': '👟',
    'botas': '🥾',
    'boots': '🥾',
    'sandalias': '👡',
    'sandals': '👡',
    'tacones': '👠',
    'heels': '👠',
    'sombrero': '👒',
    'hat': '👒',
    'gorra': '🧢',
    'cap': '🧢',
    'gafas': '👓',
    'lentes': '👓',
    'glasses': '👓',
    'sunglasses': '🕶️',
    'reloj': '⌚',
    'watch': '⌚',
    'apple watch': '⌚',
    'smartwatch': '⌚',
    'collar': '📿',
    'necklace': '📿',
    'anillo': '💍',
    'ring': '💍',
    'pulsera': '📿',
    'bracelet': '📿',
    'cinturón': '🔗',
    'belt': '🔗',
    'cartera': '👜',
    'bolso': '👜',
    'bag': '👜',
    'mochila': '🎒',
    'backpack': '🎒',
    'maleta': '🧳',
    'suitcase': '🧳',
    
    'silla': '🪑',
    'chair': '🪑',
    'mesa': '🪑',
    'table': '🪑',
    'sofá': '🛋️',
    'sofa': '🛋️',
    'cama': '🛏️',
    'bed': '🛏️',
    'colchón': '🛏️',
    'mattress': '🛏️',
    'almohada': '🛏️',
    'pillow': '🛏️',
    'sábanas': '🛏️',
    'sheets': '🛏️',
    'lámpara': '💡',
    'lamp': '💡',
    'bombilla': '💡',
    'bulb': '💡',
    'foco': '💡',
    'cortinas': '🪟',
    'curtains': '🪟',
    'espejo': '🪞',
    'mirror': '🪞',
    'cuadro': '🖼️',
    'picture': '🖼️',
    'frame': '🖼️',
    'jarrón': '🏺',
    'vase': '🏺',
    'planta': '🪴',
    'plant': '🪴',
    'maceta': '🪴',
    'pot': '🪴',
    'regadera': '🚿',
    'shower': '🚿',
    'toalla': '🛁',
    'towel': '🛁',
    'jabón': '🧼',
    'soap': '🧼',
    'shampoo': '🧴',
    'champú': '🧴',
    'detergente': '🧽',
    'detergent': '🧽',
    'escoba': '🧹',
    'broom': '🧹',
    'trapeador': '🧽',
    'mop': '🧽',
    
    'martillo': '🔨',
    'hammer': '🔨',
    'destornillador': '🪛',
    'screwdriver': '🪛',
    'taladro': '🔧',
    'drill': '🔧',
    'sierra': '🪚',
    'saw': '🪚',
    'llave': '🔧',
    'wrench': '🔧',
    'tornillo': '🔩',
    'screw': '🔩',
    'clavo': '🔨',
    'nail': '🔨',
    'pala': '🪣',
    'shovel': '🪣',
    'rastrillo': '🪣',
    'rake': '🪣',
    'manguera': '🚿',
    'hose': '🚿',
    'tijeras': '✂️',
    'scissors': '✂️',
    'podadora': '✂️',
    'trimmer': '✂️',
    
    'bicicleta': '🚴',
    'bike': '🚴',
    'bicycle': '🚴',
    'pelota': '⚽',
    'ball': '⚽',
    'fútbol': '⚽',
    'soccer': '⚽',
    'basketball': '🏀',
    'baloncesto': '🏀',
    'tennis': '🎾',
    'ping pong': '🏓',
    'volleyball': '🏐',
    'voleibol': '🏐',
    'baseball': '⚾',
    'béisbol': '⚾',
    'golf': '⛳',
    'fitness': '💪',
    'gym': '💪',
    'pesas': '🏋️',
    'weights': '🏋️',
    'dumbbell': '🏋️',
    'mancuernas': '🏋️',
    'yoga': '🧘',
    'mat': '🧘',
    'colchoneta': '🧘',
    'treadmill': '🏃',
    'caminadora': '🏃',
    'elíptica': '🏃',
    'elliptical': '🏃',
    'raqueta': '🎾',
    'racket': '🎾',
    'casco': '⛑️',
    'helmet': '⛑️',
    'patines': '🛼',
    'skates': '🛼',
    'patineta': '🛹',
    'skateboard': '🛹',
    'scooter': '🛴',
    'natación': '🏊',
    'swimming': '🏊',
    'goggles': '🥽',
    'lentes natación': '🥽',
    
    'libro': '📚',
    'book': '📚',
    'novela': '📖',
    'novel': '📖',
    'cuaderno': '📓',
    'agenda': '📅',
    'diary': '�',
    'lápiz': '✏️',
    'pencil': '✏️',
    'bolígrafo': '✒️',
    'pen': '✒️',
    'marcador': '🖍️',
    'marker': '🖍️',
    'resaltador': '🖍️',
    'highlighter': '🖍️',
    'regla': '📏',
    'ruler': '📏',
    'calculadora': '🔢',
    'calculator': '🔢',
    'mochila escolar': '🎒',
    'school bag': '🎒',
    'diccionario': '📖',
    'dictionary': '📖',
    'atlas': '🗺️',
    'map': '🗺️',
    'enciclopedia': '📚',
    'encyclopedia': '📚',
    
    'agua': '💧',
    'water': '💧',
    'refresco': '🥤',
    'soda': '🥤',
    'coca cola': '🥤',
    'pepsi': '🥤',
    'sprite': '🥤',
    'jugo': '🧃',
    'juice': '🧃',
    'naranja': '🍊',
    'orange': '🍊',
    'manzana': '🍎',
    'apple': '🍎',
    'plátano': '🍌',
    'banana': '🍌',
    'uva': '🍇',
    'grape': '🍇',
    'fresa': '🍓',
    'strawberry': '🍓',
    'piña': '🍍',
    'pineapple': '🍍',
    'sandía': '🍉',
    'watermelon': '🍉',
    'limón': '🍋',
    'lemon': '🍋',
    'tomate': '🍅',
    'tomato': '🍅',
    'zanahoria': '🥕',
    'carrot': '🥕',
    'lechuga': '🥬',
    'lettuce': '🥬',
    'cebolla': '🧅',
    'onion': '🧅',
    'papa': '🥔',
    'potato': '🥔',
    'arroz': '🍚',
    'rice': '🍚',
    'pasta': '🍝',
    'spaghetti': '🍝',
    'pan': '🍞',
    'bread': '🍞',
    'leche': '🥛',
    'milk': '🥛',
    'yogurt': '🥛',
    'queso': '🧀',
    'cheese': '🧀',
    'huevo': '🥚',
    'egg': '🥚',
    'pollo': '🍗',
    'chicken': '🍗',
    'pechuga': '🍗',
    'breast': '🍗',
    'muslo': '🍗',
    'thigh': '🍗',
    'alitas': '🍗',
    'wings': '🍗',
    'pollo entero': '🍗',
    'whole chicken': '🍗',
    'pavo': '🦃',
    'turkey': '🦃',
    'pato': '🦆',
    'duck': '🦆',
    'codorniz': '🐦',
    'quail': '🐦',
    
    'carne': '🥩',
    'meat': '🥩',
    'res': '🥩',
    'beef': '🥩',
    'bistec': '🥩',
    'steak': '🥩',
    'filete': '🥩',
    'fillet': '🥩',
    'solomillo': '🥩',
    'tenderloin': '🥩',
    'costilla': '🥩',
    'ribs': '🥩',
    'asado': '🥩',
    'roast': '🥩',
    'molida': '🥩',
    'ground beef': '🥩',
    'hamburguesa cruda': '🥩',
    'ground meat': '🥩',
    'milanesa': '🥩',
    'schnitzel': '🥩',
    'cerdo': '🥓',
    'pork': '🥓',
    'chuleta': '🥓',
    'chops': '🥓',
    'lomo': '🥓',
    'loin': '🥓',
    'tocino': '🥓',
    'bacon': '🥓',
    'jamón': '🍖',
    'ham': '🍖',
    'salchicha': '🌭',
    'sausage': '🌭',
    'chorizo': '🌭',
    'mortadela': '🍖',
    'mortadella': '🍖',
    'salami': '🍖',
    'pepperoni': '🍖',
    'cordero': '🥩',
    'lamb': '🥩',
    'cabrito': '🥩',
    'goat': '🥩',
    'venado': '🥩',
    'venison': '🥩',
    'conejo': '🐰',
    'rabbit': '🐰',
    
    'pescado': '🐟',
    'fish': '🐟',
    'salmón': '🐟',
    'salmon': '🐟',
    'atún': '🐟',
    'tuna': '🐟',
    'trucha': '🐟',
    'trout': '🐟',
    'bacalao': '🐟',
    'cod': '🐟',
    'mero': '🐟',
    'grouper': '🐟',
    'robalo': '🐟',
    'bass': '🐟',
    'tilapia': '🐟',
    'sardina': '🐟',
    'sardine': '🐟',
    'mojarra': '🐟',
    'snapper': '🐟',
    'camarón': '🦐',
    'shrimp': '🦐',
    'langosta': '🦞',
    'lobster': '🦞',
    'cangrejo': '🦀',
    'crab': '🦀',
    'jaiba': '🦀',
    'pulpo': '🐙',
    'octopus': '🐙',
    'calamar': '🦑',
    'squid': '🦑',
    'almeja': '🦪',
    'clam': '🦪',
    'ostra': '🦪',
    'oyster': '🦪',
    'mejillón': '🦪',
    'mussel': '🦪',
    'vieira': '🦪',
    'scallop': '🦪',
    'café': '☕',
    'té': '🍵',
    'tea': '🍵',
    'cerveza': '🍺',
    'beer': '🍺',
    'vino': '🍷',
    'wine': '🍷',
    'chocolate': '🍫',
    'dulce': '🍬',
    'candy': '🍬',
    'galletas': '🍪',
    'cookies': '🍪',
    'pastel': '🎂',
    'cake': '🎂',
    'helado': '🍦',
    'ice cream': '🍦',
    'pizza': '🍕',
    'hamburguesa': '🍔',
    'burger': '🍔',
    'hot dog': '🌭',
    'sandwich': '🥪',
    'taco': '🌮',
    'burrito': '🌯',
    'ensalada': '🥗',
    'salad': '🥗',
    'cereal': '🥣',
    'avena': '🥣',
    'oatmeal': '🥣',
    
    'mantequilla': '🧈',
    'butter': '🧈',
    'crema': '🥛',
    'cream': '🥛',
    'nata': '🥛',
    'crema agria': '🥛',
    'sour cream': '🥛',
    'requesón': '🧀',
    'cottage cheese': '🧀',
    'queso fresco': '🧀',
    'fresh cheese': '🧀',
    'queso manchego': '🧀',
    'cheddar': '🧀',
    'mozzarella': '🧀',
    'parmesano': '🧀',
    'parmesan': '🧀',
    'gouda': '🧀',
    'brie': '🧀',
    'camembert': '🧀',
    'ricotta': '🧀',
    'kefir': '🥛',
    'leche descremada': '🥛',
    'skim milk': '🥛',
    'leche entera': '🥛',
    'whole milk': '🥛',
    'leche deslactosada': '🥛',
    'lactose free milk': '🥛',
    'leche de almendra': '🥛',
    'almond milk': '🥛',
    'leche de coco': '🥛',
    'coconut milk': '🥛',
    'leche de soya': '🥛',
    'soy milk': '🥛',
    'leche de avena': '🥛',
    'oat milk': '🥛',
    
    'baguette': '🥖',
    'pan integral': '🍞',
    'whole wheat bread': '🍞',
    'pan tostado': '🍞',
    'toast': '🍞',
    'pan dulce': '🧁',
    'sweet bread': '🧁',
    'croissant': '🥐',
    'dona': '🍩',
    'donut': '🍩',
    'muffin': '🧁',
    'cupcake': '🧁',
    'pan de molde': '🍞',
    'sandwich bread': '🍞',
    'tortilla': '🫓',
    'tortillas': '🫓',
    'bagel': '🥯',
    'pretzel': '🥨',
    'waffle': '🧇',
    'panqueque': '🥞',
    'pancake': '🥞',
    'crepa': '🥞',
    'crepe': '🥞',
    
    'quinoa': '🌾',
    'avena cereal': '🌾',
    'oats': '🌾',
    'trigo': '🌾',
    'wheat': '🌾',
    'cebada': '🌾',
    'barley': '🌾',
    'centeno': '🌾',
    'rye': '🌾',
    'amaranto': '🌾',
    'amaranth': '🌾',
    'chía': '🌾',
    'chia': '🌾',
    'linaza': '🌾',
    'flax': '🌾',
    'ajonjolí': '🌾',
    'sesame': '🌾',
    'granola': '🥣',
    'muesli': '🥣',
    'corn flakes': '🥣',
    'hojuelas': '🥣',
    
    'frijol': '🫘',
    'beans': '🫘',
    'lentejas': '🫘',
    'lentils': '🫘',
    'garbanzos': '🫘',
    'chickpeas': '🫘',
    'habas': '🫘',
    'fava beans': '🫘',
    'chicharos': '🫛',
    'peas': '🫛',
    'ejotes': '🫛',
    'green beans': '🫛',
    'almendras': '🥜',
    'almonds': '🥜',
    'nueces': '🥜',
    'walnuts': '🥜',
    'pistachos': '🥜',
    'pistachios': '🥜',
    'cacahuates': '🥜',
    'peanuts': '🥜',
    'avellanas': '🥜',
    'hazelnuts': '🥜',
    'pecanas': '🥜',
    'pecans': '🥜',
    'castañas': '🌰',
    'chestnuts': '🌰',
    'piñones': '🥜',
    'pine nuts': '🥜',
    'anacardos': '🥜',
    'cashews': '🥜',
    
    'sal': '🧂',
    'salt': '🧂',
    'pimienta': '🧂',
    'pepper': '🧂',
    'canela': '🧂',
    'cinnamon': '🧂',
    'comino': '🧂',
    'cumin': '🧂',
    'orégano': '🌿',
    'oregano': '🌿',
    'albahaca': '🌿',
    'basil': '🌿',
    'perejil': '🌿',
    'parsley': '🌿',
    'cilantro': '🌿',
    'coriander': '🌿',
    'tomillo': '🌿',
    'thyme': '🌿',
    'romero': '🌿',
    'rosemary': '🌿',
    'laurel': '🌿',
    'bay leaves': '🌿',
    'ajo': '🧄',
    'garlic': '🧄',
    'jengibre': '🧄',
    'ginger': '🧄',
    'cúrcuma': '🧂',
    'turmeric': '🧂',
    'paprika': '🧂',
    'azafrán': '🧂',
    'saffron': '🧂',
    'vainilla': '🧂',
    'vanilla': '🧂',
    'vinagre': '🧂',
    'vinegar': '🧂',
    'aceite oliva': '🫒',
    'olive oil': '🫒',
    'aceite': '🫒',
    'oil': '🫒',
    'mayonesa': '🥪',
    'mayonnaise': '🥪',
    'mostaza': '🥪',
    'mustard': '🥪',
    'ketchup': '🍅',
    'salsa': '🌶️',
    'sauce': '🌶️',
    'chile': '🌶️',
    'chili': '🌶️',
    'jalapeño': '🌶️',
    'habanero': '🌶️',
    'serrano': '🌶️',
    'chipotle': '🌶️',
    
    'brócoli': '🥦',
    'broccoli': '🥦',
    'coliflor': '🥦',
    'cauliflower': '🥦',
    'espinaca': '🥬',
    'spinach': '🥬',
    'acelga': '🥬',
    'chard': '🥬',
    'kale': '🥬',
    'col': '🥬',
    'cabbage': '🥬',
    'col rizada': '🥬',
    'apio': '🥬',
    'celery': '🥬',
    'pepino': '🥒',
    'cucumber': '🥒',
    'calabaza': '🎃',
    'pumpkin': '🎃',
    'calabacín': '🥒',
    'zucchini': '🥒',
    'berenjena': '🍆',
    'eggplant': '🍆',
    'pimiento': '🫑',
    'bell pepper': '🫑',
    'maíz': '🌽',
    'corn': '🌽',
    'elote': '🌽',
    'rábano': '🥕',
    'radish': '🥕',
    'betabel': '🥕',
    'beet': '🥕',
    'nabo': '🥕',
    'turnip': '🥕',
    'camote': '🍠',
    'sweet potato': '🍠',
    'chayote': '🥒',
    'nopal': '🌵',
    'cactus': '🌵',
    'hongos': '🍄',
    'mushrooms': '🍄',
    'champiñones': '🍄',
    'setas': '🍄',
    
    'coco': '🥥',
    'coconut': '🥥',
    'aguacate': '🥑',
    'avocado': '🥑',
    'kiwi': '🥝',
    'mango': '🥭',
    'papaya': '🍈',
    'melón': '🍈',
    'melon': '🍈',
    'durazno': '🍑',
    'peach': '🍑',
    'pera': '🍐',
    'pear': '🍐',
    'cereza': '🍒',
    'cherry': '🍒',
    'ciruela': '🍇',
    'plum': '🍇',
    'higo': '🍇',
    'fig': '🍇',
    'granada': '🍇',
    'pomegranate': '🍇',
    'arándano': '🫐',
    'blueberry': '🫐',
    'frambuesa': '🍓',
    'raspberry': '🍓',
    'mora': '🍓',
    'blackberry': '🍓',
    'grosella': '🍓',
    'currant': '🍓',
    'maracuyá': '🍈',
    'passion fruit': '🍈',
    'lichi': '🍈',
    'lychee': '🍈',
    'guayaba': '🍈',
    'guava': '🍈',
    'mamey': '🍈',
    'zapote': '🍈',
    'tuna fruta': '🍈',
    'pitaya': '🍈',
    'dragon fruit': '🍈',
    
    'atún enlatado': '🥫',
    'canned tuna': '🥫',
    'sardinas': '🥫',
    'canned sardines': '🥫',
    'salmón enlatado': '🥫',
    'canned salmon': '🥫',
    'frijoles enlatados': '🥫',
    'canned beans': '🥫',
    'chícharos enlatados': '🥫',
    'canned peas': '🥫',
    'elote enlatado': '🥫',
    'canned corn': '🥫',
    'jitomate enlatado': '🥫',
    'canned tomatoes': '🥫',
    'puré tomate': '🥫',
    'tomato paste': '🥫',
    'champiñones enlatados': '🥫',
    'canned mushrooms': '🥫',
    'duraznos en almíbar': '🥫',
    'canned peaches': '🥫',
    'piña en almíbar': '🥫',
    'canned pineapple': '🥫',
    'conservas': '🥫',
    'preserves': '🥫',
    'mermelada': '🍯',
    'jam': '🍯',
    'jalea': '🍯',
    'jelly': '🍯',
    'miel': '🍯',
    'honey': '🍯',
    'cajeta': '🍯',
    'dulce leche': '🍯',
    'nutella': '🍯',
    'mantequilla maní': '🥜',
    'peanut butter': '🥜',
    
    'helado cremoso': '🍦',
    'ice cream premium': '🍦',
    'paleta': '🍧',
    'popsicle': '🍧',
    'yogurt congelado': '🍧',
    'frozen yogurt': '🍧',
    'verduras congeladas': '❄️',
    'frozen vegetables': '❄️',
    'frutas congeladas': '❄️',
    'frozen fruits': '❄️',
    'pescado congelado': '❄️',
    'frozen fish': '❄️',
    'pollo congelado': '❄️',
    'frozen chicken': '❄️',
    'carne congelada': '❄️',
    'frozen meat': '❄️',
    'pizza congelada': '❄️',
    'frozen pizza': '❄️',
    'lasaña congelada': '❄️',
    'frozen lasagna': '❄️',
    'waffles congelados': '❄️',
    'frozen waffles': '❄️',
    'papas fritas congeladas': '❄️',
    'frozen fries': '❄️',
    
    'papas fritas': '🍟',
    'chips': '🍟',
    'nachos': '🌽',
    'doritos': '🌽',
    'cheetos': '🧀',
    'palomitas': '🍿',
    'popcorn': '🍿',
    'pretzels': '🥨',
    'crackers': '🍪',
    'galletas saladas': '🍪',
    'nuts': '🥜',
    'nueces mixtas': '🥜',
    'trail mix': '🥜',
    'granola bar': '🍫',
    'barra granola': '🍫',
    'cereal bar': '🍫',
    'barra cereal': '🍫',
    'chocolate bar': '🍫',
    'barra chocolate': '🍫',
    'gominolas': '🍬',
    'gummies': '🍬',
    'chicle': '🍬',
    'gum': '🍬',
    'mentas': '🍬',
    'mints': '🍬',
    'caramelos': '🍬',
    'candies': '🍬',
    'malvaviscos': '🍬',
    'marshmallows': '🍬',
    
    'pan integral industrial': '🍞',
    'pan blanco': '🍞',
    'white bread': '🍞',
    'pan multigrano': '🍞',
    'multigrain bread': '🍞',
    'pan pita': '🫓',
    'pita bread': '🫓',
    'tortillas harina': '🫓',
    'flour tortillas': '🫓',
    'tortillas maíz': '🌽',
    'corn tortillas': '🌽',
    'tostadas': '🌽',
    'pasta italiana': '🍝',
    'spaghetti italiano': '🍝',
    'macarrones': '🍝',
    'macaroni': '🍝',
    'penne': '🍝',
    'fettuccine': '🍝',
    'linguine': '🍝',
    'ravioli': '🍝',
    'lasaña': '🍝',
    'lasagna': '🍝',
    'fideos': '🍜',
    'noodles': '🍜',
    'ramen': '🍜',
    'sopa instantánea': '🍜',
    'instant soup': '🍜',
    
    'cerveza nacional': '🍺',
    'beer nacional': '🍺',
    'cerveza light': '🍺',
    'light beer': '🍺',
    'cerveza artesanal': '🍺',
    'craft beer': '🍺',
    'vino tinto': '🍷',
    'red wine': '🍷',
    'vino blanco': '🍷',
    'white wine': '🍷',
    'champagne': '🍾',
    'champaña': '🍾',
    'espumoso': '🍾',
    'sparkling wine': '🍾',
    'tequila': '🍸',
    'whisky': '🥃',
    'whiskey': '🥃',
    'ron': '🥃',
    'rum': '🥃',
    'vodka': '🍸',
    'gin': '🍸',
    'brandy': '🥃',
    'cognac': '🥃',
    'licor': '🍸',
    'liqueur': '🍸',
    
    'agua mineral': '💧',
    'mineral water': '💧',
    'agua con gas': '💧',
    'sparkling water': '💧',
    'agua saborizada': '🥤',
    'flavored water': '🥤',
    'bebida energética': '⚡',
    'energy drink': '⚡',
    'bebida deportiva': '🥤',
    'sports drink': '🥤',
    'kombucha': '🧪',
    'té helado': '🧊',
    'iced tea': '🧊',
    'café frío': '🧊',
    'cold brew': '🧊',
    'frappé': '🧊',
    'smoothie': '🥤',
    'batido': '🥤',
    'milkshake': '🥛',
    'malteada': '🥛',
    
    'quinoa orgánica': '🌾',
    'proteína en polvo': '💪',
    'protein powder': '💪',
    'barras proteína': '💪',
    'protein bars': '💪',
    'suplemento': '💊',
    'supplement': '💊',
    'vitaminas': '💊',
    'vitamins': '💊',
    'omega 3': '💊',
    'probióticos': '💊',
    'probiotics': '💊',
    'colágeno': '💊',
    'collagen': '💊',
    'stevia': '🌿',
    'endulzante': '🌿',
    'sweetener': '🌿',
    'azúcar morena': '🧈',
    'brown sugar': '🧈',
    'azúcar': '🧈',
    'sugar': '🧈',
    'sal marina': '🧂',
    'sea salt': '🧂',
    'sal rosa': '🧂',
    'pink salt': '🧂',
    
    'sushi': '🍣',
    'sashimi': '🍣',
    'wasabi': '🟢',
    'salsa soya': '🍜',
    'soy sauce': '🍜',
    'teriyaki': '🍜',
    'miso': '🍜',
    'kimchi': '🌶️',
    'curry': '🍛',
    'garam masala': '🧂',
    'cous cous': '🍚',
    'hummus': '🫘',
    'tahini': '🥜',
    'falafel': '🫘',
    'pesto': '🌿',
    'balsámico': '🫒',
    'balsamic': '🫒',
    'aceitunas': '🫒',
    'olives': '🫒',
    'alcaparras': '🫒',
    'capers': '🫒',
    
    'chile en polvo': '🌶️',
    'chili powder': '🌶️',
    'chile piquín': '🌶️',
    'chile ancho': '🌶️',
    'chile guajillo': '🌶️',
    'chile pasilla': '🌶️',
    'chile mulato': '🌶️',
    'achiote': '🌶️',
    'epazote': '🌿',
    'hoja santa': '🌿',
    'hierba buena': '🌿',
    'mexican mint': '🌿',
    'masa harina': '🌽',
    'corn flour': '🌽',
    'nixtamal': '🌽',
    'hominy': '🌽',
    'pozole': '🌽',
    'tamales': '🌽',
    'tamal': '🌽',
    'mole': '🍫',
    'mole poblano': '🍫',
    'mole negro': '🍫',
    'pipián': '🌶️',
    'adobo': '🌶️',
    'recado rojo': '🌶️',
    'cochinita': '🥩',
    'carnitas': '🥩',
    'barbacoa': '🥩',
    'machaca': '🥩',
    'cecina': '🥩',
    'tasajo': '🥩',
    'chorizo mexicano': '🌭',
    'longaniza': '🌭',
    'chicharrón': '🥓',
    'pork rinds': '🥓',
    'queso fresco mexicano': '🧀',
    'queso oaxaca': '🧀',
    'queso panela': '🧀',
    'queso cotija': '🧀',
    'queso manchego mexicano': '🧀',
    'requesón mexicano': '🧀',
    'crema mexicana': '🥛',
    'mexican cream': '🥛',
    'piloncillo': '🧈',
    'brown sugar cone': '🧈',
    'dulce calabaza': '🍯',
    'pumpkin candy': '🍯',
    'ate': '🍯',
    'fruit paste': '🍯',
    'tejocotes': '🍊',
    'mexican hawthorn': '🍊',
    'jicama': '🥕',
    'verdolagas': '🥬',
    'purslane': '🥬',
    'quelites': '🥬',
    'wild greens': '🥬',
    'flor calabaza': '🌻',
    'squash blossoms': '🌻',
    'huitlacoche': '🌽',
    'corn fungus': '🌽',
    'nopales': '🌵',
    'cactus paddles': '🌵',
    'tomatillo': '🍅',
    'mexican tomato': '🍅',
    'chile poblano': '🫑',
    'poblano pepper': '🫑',
    'rajas': '🫑',
    'pepper strips': '🫑',
    'elote preparado': '🌽',
    'mexican corn': '🌽',
    'esquites': '🌽',
    'corn kernels': '🌽',
    'agua fresca': '🥤',
    'flavored water mexican': '🥤',
    'horchata': '🥛',
    'rice drink': '🥛',
    'jamaica': '🌺',
    'hibiscus': '🌺',
    'tamarindo': '🍈',
    'tamarind': '🍈',
    'tejuino': '🌽',
    'fermented corn drink': '🌽',
    'pulque': '🍺',
    'agave drink': '🍺',
    'mezcal': '🍸',
    'agave spirit': '🍸',
    'cempasúchil': '🌻',
    'marigold': '🌻',
    'chocolate mexicano': '🍫',
    'mexican chocolate': '🍫',
    'chocolate abuelita': '🍫',
    'canela mexicana': '🧂',
    'mexican cinnamon': '🧂',
    'vainilla mexicana': '🧂',
    'mexican vanilla': '🧂',
    'cloro': '🧽',
    'bleach': '🧽',
    'limpiador': '🧽',
    'cleaner': '🧽',
    'desinfectante': '🧼',
    'disinfectant': '🧼',
    'papel higiénico': '🧻',
    'toilet paper': '🧻',
    'servilletas': '🧻',
    'napkins': '🧻',
    'pañuelos': '🧻',
    'tissues': '🧻',
    'basura': '🗑️',
    'trash': '🗑️',
    'bolsas': '�️',
    'bags': '🛍️',
    
    'cepillo dientes': '🪥',
    'toothbrush': '🪥',
    'pasta dental': '🦷',
    'toothpaste': '🦷',
    'enjuague': '🦷',
    'mouthwash': '🦷',
    'perfume': '💐',
    'cologne': '💐',
    'desodorante': '💐',
    'deodorant': '💐',
    'crema facial': '🧴',
    'cream facial': '🧴',
    'loción': '🧴',
    'lotion': '🧴',
    'bloqueador': '🧴',
    'sunscreen': '🧴',
    'maquillaje': '💄',
    'makeup': '💄',
    'labial': '💄',
    'lipstick': '💄',
    'base': '💄',
    'foundation': '💄',
    'máscara': '💄',
    'mascara': '💄',
    'peine': '�',
    'comb': '🪮',
    'cepillo': '🪮',
    'brush': '🪮',
    
    'pañal': '👶',
    'diaper': '👶',
    'biberón': '🍼',
    'bottle': '🍼',
    'chupón': '👶',
    'pacifier': '👶',
    'carriola': '👶',
    'stroller': '👶',
    'cuna': '👶',
    'crib': '👶',
    'juguete': '🧸',
    'toy': '🧸',
    'peluche': '🧸',
    'stuffed': '🧸',
    
    'comida perro': '🐕',
    'dog food': '🐕',
    'comida gato': '🐱',
    'cat food': '🐱',
    'collar perro': '🐕',
    'dog collar': '🐕',
    'juguete perro': '🐕',
    'dog toy': '🐕',
    'arena gato': '🐱',
    'cat litter': '🐱',
    'correa': '🐕',
    'leash': '🐕',
    'pecera': '🐠',
    'aquarium': '🐠',
    'comida pez': '🐠',
    'fish food': '🐠',
    
    'default': '📦',
    'genérico': '📦',
    'otro': '📦',
    'varios': '📦',
    'misceláneo': '📦'
};

export const coloredIcons = {
    'iphone': '📱',
    'laptop': '💻',
    'headphones': '🎧',
    'gaming': '🎮',
    'tv': '📺',
    'watch': '⌚',
    'book': '📚',
    'food': '🍎',
    'drink': '🥤',
    'clothes': '👔',
    'home': '🏠',
    'sports': '⚽',
    'health': '💊',
    'baby': '👶',
    'pet': '🐕',
    'tool': '🔧',
    'clean': '🧽',
    'default': '📦'
};

export const getProductIcon = (nombreProducto) => {
    if (!nombreProducto || typeof nombreProducto !== 'string') {
        return iconMapping.default;
    }
    
    const nombreLower = nombreProducto.toLowerCase();
    
    for (const [keyword, icon] of Object.entries(iconMapping)) {
        if (nombreLower.includes(keyword.toLowerCase())) {
            return icon;
        }
    }
    
    return iconMapping.default;
};

export const getColoredProductIcon = (nombreProducto) => {
    if (!nombreProducto || typeof nombreProducto !== 'string') {
        return coloredIcons.default;
    }
    
    const nombreLower = nombreProducto.toLowerCase();
    
    if (nombreLower.includes('iphone') || nombreLower.includes('phone') || nombreLower.includes('celular')) return '📱';
    if (nombreLower.includes('laptop') || nombreLower.includes('computadora') || nombreLower.includes('pc')) return '💻';
    if (nombreLower.includes('auricular') || nombreLower.includes('headphone') || nombreLower.includes('speaker')) return '🎧';
    if (nombreLower.includes('gaming') || nombreLower.includes('gamer') || nombreLower.includes('xbox') || nombreLower.includes('playstation')) return '🎮';
    if (nombreLower.includes('tv') || nombreLower.includes('televisor') || nombreLower.includes('monitor')) return '📺';
    if (nombreLower.includes('watch') || nombreLower.includes('reloj')) return '⌚';
    
    if (nombreLower.includes('agua') || nombreLower.includes('water')) return '💧';
    if (nombreLower.includes('refresco') || nombreLower.includes('soda') || nombreLower.includes('coca')) return '🥤';
    if (nombreLower.includes('café') || nombreLower.includes('coffee')) return '☕';
    if (nombreLower.includes('manzana') || nombreLower.includes('apple')) return '🍎';
    if (nombreLower.includes('naranja') || nombreLower.includes('orange')) return '🍊';
    if (nombreLower.includes('plátano') || nombreLower.includes('banana')) return '🍌';
    if (nombreLower.includes('leche') || nombreLower.includes('milk')) return '🥛';
    if (nombreLower.includes('pan') || nombreLower.includes('bread')) return '🍞';
    if (nombreLower.includes('pizza')) return '🍕';
    if (nombreLower.includes('hamburguesa') || nombreLower.includes('burger')) return '🍔';
    
    if (nombreLower.includes('camisa') || nombreLower.includes('shirt')) return '�';
    if (nombreLower.includes('pantalón') || nombreLower.includes('pants') || nombreLower.includes('jeans')) return '👖';
    if (nombreLower.includes('zapatos') || nombreLower.includes('shoes') || nombreLower.includes('tenis')) return '👟';
    if (nombreLower.includes('vestido') || nombreLower.includes('dress')) return '👗';
    
    if (nombreLower.includes('silla') || nombreLower.includes('chair')) return '🪑';
    if (nombreLower.includes('lámpara') || nombreLower.includes('lamp') || nombreLower.includes('bombilla')) return '💡';
    if (nombreLower.includes('refrigerador') || nombreLower.includes('nevera')) return '❄️';
    if (nombreLower.includes('lavadora') || nombreLower.includes('washing')) return '🫧';
    
    if (nombreLower.includes('pelota') || nombreLower.includes('ball') || nombreLower.includes('fútbol')) return '⚽';
    if (nombreLower.includes('bicicleta') || nombreLower.includes('bike')) return '�';
    if (nombreLower.includes('fitness') || nombreLower.includes('gym') || nombreLower.includes('pesas')) return '💪';
    
    if (nombreLower.includes('libro') || nombreLower.includes('book')) return '📚';
    if (nombreLower.includes('cuaderno') || nombreLower.includes('notebook')) return '📓';
    if (nombreLower.includes('lápiz') || nombreLower.includes('pencil')) return '✏️';
    
    if (nombreLower.includes('shampoo') || nombreLower.includes('champú')) return '🧴';
    if (nombreLower.includes('jabón') || nombreLower.includes('soap')) return '🧼';
    if (nombreLower.includes('perfume') || nombreLower.includes('cologne')) return '💐';
    if (nombreLower.includes('maquillaje') || nombreLower.includes('makeup')) return '💄';
    
    if (nombreLower.includes('pañal') || nombreLower.includes('diaper')) return '👶';
    if (nombreLower.includes('biberón') || nombreLower.includes('bottle')) return '�';
    if (nombreLower.includes('juguete') || nombreLower.includes('toy')) return '🧸';
    
    if (nombreLower.includes('perro') || nombreLower.includes('dog')) return '�';
    if (nombreLower.includes('gato') || nombreLower.includes('cat')) return '🐱';
    if (nombreLower.includes('pez') || nombreLower.includes('fish')) return '🐠';
    
    if (nombreLower.includes('limpiador') || nombreLower.includes('cleaner') || nombreLower.includes('cloro')) return '🧽';
    if (nombreLower.includes('detergente') || nombreLower.includes('detergent')) return '🧽';
    if (nombreLower.includes('escoba') || nombreLower.includes('broom')) return '🧹';
    
    return coloredIcons.default;
};

export const getIconByCategory = (categoria) => {
    const categoryMapping = {
        'tecnologia': '💻',
        'technology': '💻',
        'electronica': '🔌',
        'electronics': '🔌',
        'computacion': '💻',
        'computing': '💻',
        'telefonia': '📱',
        'mobile': '📱',
        'audio': '🎧',
        'sonido': '🎧',
        'gaming': '🎮',
        'videojuegos': '🎮',
        
        'hogar': '🏠',
        'home': '🏠',
        'electrodomesticos': '❄️',
        'appliances': '❄️',
        'muebles': '🪑',
        'furniture': '🪑',
        'decoracion': '🖼️',
        'decoration': '🖼️',
        'jardin': '🪴',
        'garden': '🪴',
        'herramientas': '🔧',
        'tools': '🔧',
        'limpieza': '🧽',
        'cleaning': '🧽',
        
        'ropa': '�',
        'clothing': '👔',
        'moda': '👗',
        'fashion': '👗',
        'zapatos': '👟',
        'shoes': '👟',
        'accesorios': '💍',
        'accessories': '💍',
        'joyeria': '💍',
        'jewelry': '💍',
        'relojes': '⌚',
        'watches': '⌚',
        
        'deportes': '⚽',
        'sports': '⚽',
        'fitness': '💪',
        'ejercicio': '💪',
        'exercise': '💪',
        'outdoor': '🏕️',
        'aire libre': '🏕️',
        'camping': '🏕️',
        'ciclismo': '🚴',
        'cycling': '�',
        
        'comida': '🍎',
        'food': '🍎',
        'alimentos': '🍎',
        'bebidas': '🥤',
        'drinks': '🥤',
        'lacteos': '🥛',
        'dairy': '🥛',
        'frutas': '🍊',
        'fruits': '🍊',
        'verduras': '🥕',
        'vegetables': '🥕',
        'carnes': '🥩',
        'meat': '🥩',
        'panaderia': '🍞',
        'bakery': '🍞',
        'dulces': '🍬',
        'candy': '🍬',
        'snacks': '🍿',
        'botanas': '�',
        
        'salud': '💊',
        'health': '💊',
        'belleza': '💄',
        'beauty': '💄',
        'cuidado personal': '🧴',
        'personal care': '🧴',
        'farmacia': '💊',
        'pharmacy': '💊',
        'cosmeticos': '💄',
        'cosmetics': '💄',
        'perfumes': '💐',
        'fragrances': '💐',
        
        'bebes': '👶',
        'babies': '👶',
        'niños': '🧸',
        'kids': '🧸',
        'juguetes': '🧸',
        'toys': '🧸',
        'infantil': '👶',
        'children': '🧸',
        'maternidad': '👶',
        'maternity': '👶',
        
        'mascotas': '🐕',
        'pets': '🐕',
        'perros': '🐕',
        'dogs': '🐕',
        'gatos': '🐱',
        'cats': '🐱',
        'animales': '🐕',
        'animals': '🐕',
        'veterinaria': '🐕',
        'veterinary': '�',
        
        'libros': '📚',
        'books': '📚',
        'educacion': '📚',
        'education': '📚',
        'papeleria': '📝',
        'stationery': '📝',
        'oficina': '📎',
        'office': '📎',
        'escolar': '🎒',
        'school': '🎒',
        
        'automotriz': '🚗',
        'automotive': '🚗',
        'auto': '🚗',
        'car': '🚗',
        'vehiculos': '🚗',
        'vehicles': '🚗',
        'repuestos': '🔧',
        'parts': '🔧',
        'llantas': '🛞',
        'tires': '🛞',
        
        'entretenimiento': '🎬',
        'entertainment': '🎬',
        'musica': '🎵',
        'music': '🎵',
        'peliculas': '🎬',
        'movies': '🎬',
        'instrumentos': '🎸',
        'instruments': '🎸',
        
        'default': '📦',
        'general': '📦',
        'varios': '📦',
        'other': '📦',
        'otros': '📦'
    };
    
    if (!categoria || typeof categoria !== 'string') {
        return categoryMapping.default;
    }
    
    const categoriaLower = categoria.toLowerCase();
    return categoryMapping[categoriaLower] || categoryMapping.default;
};

export default {
    getProductIcon,
    getColoredProductIcon,
    getIconByCategory,
    iconMapping,
    coloredIcons
};